layout_spectrum: 0.9087352850474417
typography_spectrum: 0.4422883440274745
color:
  brandStrength: 0.4863013066351414
  lightness: 0.0675493108574301
  saturation: 0.7970645304303616
  rhythmicContrast: 0.9762254899833351
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: innovative headsets
